language: python
install:
  - pip install -r requirements.txt
branches:
  only:
    - master
before_script:
  - export TZ=Asia/Shanghai
script:
  - python main.py
before_deploy:
  - if [ $CNAME ]; then
    echo $CNAME > build/CNAME;
    fi
deploy:
  provider: pages
  name: kcwikizh
  email: dev@kcwiki.moe
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: build
  on:
    branch: master
    condition: $GITHUB_TOKEN
